# Generated by Django 4.2.1 on 2023-10-04 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_profile_first_name_remove_profile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='password',
        ),
    ]
