# Generated by Django 4.2.1 on 2023-11-17 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_candidate_image_election_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('current_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('nonce', models.IntegerField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.election')),
            ],
        ),
    ]
